In [36]:
import pandas as pd
file_path = r"C:\Users\fredd\Downloads\file (2).csv"
data = pd.read_csv(file_path)
data.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0

In [37]:
#Trouver les valeurs nulles par colonnes et les remplacer par la moyenne de celle-ci
data.isnull().sum()

Make           4
Model          4
Type           4
Origin         4
DriveTrain     4
MSRP           4
Invoice        4
EngineSize     4
Cylinders      6
Horsepower     4
MPG_City       4
MPG_Highway    4
Weight         4
Wheelbase      4
Length         4
dtype: int64

In [49]:
#regrouper les colonnes en int 
columns_to_fill = ['EngineSize', 'Cylinders', 'Horsepower', 'MPG_City', 'MPG_Highway', 'Weight', 'Wheelbase', 'Length']

#boucle for pour remplacer les valeurs nulles par la moyenne de la colonne
for column in columns_to_fill : 
    data[column].fillna(data[column].mean(), inplace = True)

data.head(50)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.500000,6.000000,265.000000,17.000000,23.000000,4451.000000,106.000000,189.00000
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.000000,4.000000,200.000000,24.000000,31.000000,2778.000000,101.000000,172.00000
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.400000,4.000000,200.000000,22.000000,29.000000,3230.000000,105.000000,183.00000
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.200000,6.000000,270.000000,20.000000,28.000000,3575.000000,108.000000,186.00000
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.500000,6.000000,225.000000,18.000000,24.000000,3880.000000,115.000000,197.00000
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.500000,6.000000,225.000000,18.000000,24.000000,3893.000000,115.000000,197.00000
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.200000,6.000000,290.000000,17.000000,24.000000,3153.000000,100.000000,174.00000
7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940","$23,508",1.800000,4.000000,170.000000,22.000000,31.000000,3252.000000,104.000000,179.00000
8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940","$32,506",1.800000,4.000000,170.000000,23.000000,30.000000,3638.000000,105.000000,180.00000
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.000000,6.000000,220.000000,20.000000,28.000000,3462.000000,104.000000,179.00000
10,Audi,A4 3.0 Quattro 4dr manual,Sedan,Europe,All,"$33,430","$30,366",3.000000,6.000000,220.000000,17.000000,26.000000,3583.000000,104.000000,179.00000
11,Audi,A4 3.0 Quattro 4dr auto,Sedan,Europe,All,"$34,480","$31,388",3.000000,6.000000,220.000000,18.000000,25.000000,3627.000000,104.000000,179.00000
12,Audi,A6 3.0 4dr,Sedan,Europe,Front,"$36,640","$33,129",3.000000,6.000000,220.000000,20.000000,27.000000,3561.000000,109.000000,192.00000
13,Audi,A6 3.0 Quattro 4dr,Sedan,Europe,All,"$39,640","$35,992",3.000000,6.000000,220.000000,18.000000,25.000000,3880.000000,109.000000,192.00000
14,Audi,A4 3.0 convertible 2dr,Sedan,Europe,Front,"$42,490","$38,325",3.000000,6.000000,220.000000,20.000000,27.000000,3814.000000,105.000000,180.00000
15,Audi,A4 3.0 Quattro convertible 2dr,Sedan,Europe,All,"$44,240","$40,075",3.000000,6.000000,220.000000,18.000000,25.000000,4013.000000,105.000000,180.00000
16,Audi,A6 2.7 Turbo Quattro 4dr,Sedan,Europe,All,"$42,840","$38,840",2.700000,6.000000,250.000000,18.000000,25.000000,3836.000000,109.000000,192.00000
17,Audi,A6 4.2 Quattro 4dr,Sedan,Europe,All,"$49,690","$44,936",4.200000,8.000000,300.000000,17.000000,24.000000,4024.000000,109.000000,193.00000
18,Audi,A8 L Quattro 4dr,Sedan,Europe,All,"$69,190","$64,740",4.200000,8.000000,330.000000,17.000000,24.000000,4399.000000,121.000000,204.00000
19,Audi,S4 Quattro 4dr,Sedan,Europe,All,"$48,040","$43,556",4.200000,8.000000,340.000000,14.000000,20.000000,3825.000000,104.000000,179.00000
20,Audi,RS 6 4dr,Sports,Europe,Front,"$84,600","$76,417",4.200000,8.000000,450.000000,15.000000,22.000000,4024.000000,109.000000,191.00000
21,Audi,TT 1.8 convertible 2dr (coupe),Sports,Europe,Front,"$35,940","$32,512",1.800000,4.000000,180.000000,20.000000,28.000000,3131.000000,95.000000,159.00000
22,Audi,TT 1.8 Quattro 2dr (convertible),Sports,Europe,All,"$37,390","$33,891",1.800000,4.000000,225.000000,20.000000,28.000000,2921.000000,96.000000,159.00000
23,Audi,TT 3.2 coupe 2dr (convertible),Sports,Europe,All,"$40,590","$36,739",3.200000,6.000000,250.000000,21.000000,29.000000,3351.000000,96.000000,159.00000
24,Audi,A6 3.0 Avant Quattro,Wagon,Europe,All,"$40,840","$37,060",3.000000,6.000000,220.000000,18.000000,25.000000,4035.000000,109.000000,192.00000
25,Audi,S4 Avant Quattro,Wagon,Europe,All,"$49,090","$44,446",4.200000,8.000000,340.000000,15.000000,21.000000,3936.000000,104.000000,179.00000
26,BMW,X3 3.0i,SUV,Europe,All,"$37,000","$33,873",3.000000,6.000000,225.000000,16.000000,23.000000,4023.000000,110.000000,180.00000
27,BMW,X5 4.4i,SUV,Europe,All,"$52,195","$47,720",4.400000,8.000000,325.000000,16.000000,22.000000,4824.000000,111.000000,184.00000
28,BMW,325i 4dr,Sedan,Europe,Rear,"$28,495","$26,155",2.500000,6.000000,184.000000,20.000000,29.000000,3219.000000,107.000000,176.00000
29,BMW,325Ci 2dr,Sedan,Europe,Rear,"$30,795","$28,245",2.500000,6.000000,184.000000,20.000000,29.000000,3197.000000,107.000000,177.00000
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.196729,5.807512,215.885514,20.060748,26.843458,3577.953271,108.154206,186.36215
31,BMW,325Ci convertible 2dr,Sedan,Europe,Rear,"$37,995","$34,800",2.500000,6.000000,184.000000,19.000000,27.000000,3560.000000,107.000000,177.00000
32,BMW,325xi 4dr,Sedan,Europe,All,"$30,245","$27,745",2.500000,6.000000,184.000000,19.000000,27.000000,3461.000000,107.000000,176.00000
33,BMW,330i 4dr,Sedan,Europe,Rear,"$35,495","$32,525",3.000000,6.000000,225.000000,20.000000,30.000000,3285.000000,107.000000,176.00000
34,BMW,330Ci 2dr,Sedan,Europe,Rear,"$36,995","$33,890",3.000000,6.000000,225.000000,20.000000,30.000000,3285.000000,107.000000,176.00000
35,BMW,330xi 4dr,Sedan,Europe,All,"$37,245","$34,115",3.000000,6.000000,225.000000,20.000000,29.000000,3483.000000,107.000000,176.00000
36,BMW,525i 4dr,Sedan,Europe,Rear,"$39,995","$36,620",2.500000,6.000000,184.000000,19.000000,28.000000,3428.000000,114.000000,191.00000
37,BMW,330Ci convertible 2dr,Sedan,Europe,Rear,"$44,295","$40,530",3.000000,6.000000,225.000000,19.000000,28.000000,3616.000000,107.000000,177.00000
38,BMW,530i 4dr,Sedan,Europe,Rear,"$44,995","$41,170",3.000000,6.000000,225.000000,20.000000,30.000000,3472.000000,114.000000,191.00000
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.196729,5.807512,215.885514,20.060748,26.843458,3577.953271,108.154206,186.36215
40,BMW,545iA 4dr,Sedan,Europe,Rear,"$54,995","$50,270",4.400000,8.000000,325.000000,18.000000,26.000000,3814.000000,114.000000,191.00000
41,BMW,745i 4dr,Sedan,Europe,Rear,"$69,195","$63,190",4.400000,8.000000,325.000000,18.000000,26.000000,4376.000000,118.000000,198.00000
42,BMW,745Li 4dr,Sedan,Europe,Rear,"$73,195","$66,830",4.400000,8.000000,325.000000,18.000000,26.000000,4464.000000,123.000000,204.00000
43,BMW,M3 coupe 2dr,Sports,Europe,Rear,"$48,195","$44,170",3.200000,6.000000,333.000000,16.000000,24.000000,3415.000000,108.000000,177.00000
44,BMW,M3 convertible 2dr,Sports,Europe,Rear,"$56,595","$51,815",3.200000,6.000000,333.000000,16.000000,23.000000,3781.000000,108.000000,177.00000
45,BMW,Z4 convertible 2.5i 2dr,Sports,Europe,Rear,"$33,895","$31,065",2.500000,6.000000,184.000000,20.000000,28.000000,2932.000000,98.000000,161.00000
46,BMW,Z4 convertible 3.0i 2dr,Sports,Europe,Rear,"$41,045","$37,575",3.000000,6.000000,225.000000,21.000000,29.000000,2998.000000,98.000000,161.00000
47,BMW,325xi Sport,Wagon,Europe,All,"$32,845","$30,110",2.500000,6.000000,184.000000,19.000000,26.000000,3594.000000,107.000000,176.00000
48,Buick,Rainier,SUV,USA,All,"$37,895","$34,357",4.200000,6.000000,275.000000,15.000000,21.000000,4600.000000,113.000000,193.00000
49,Buick,Rendezvous CX,SUV,USA,Front,"$26,545","$24,085",3.400000,6.000000,185.000000,19.000000,26.000000,4024.000000,112.000000,187.00000

In [50]:
data['Horsepower'].mean()

215.8855140186916

In [53]:
#observer les différents type de Make et leurs fréquences
data['Make'].value_counts()

Make
Toyota           28
Chevrolet        27
Mercedes-Benz    26
Ford             23
BMW              20
Audi             19
Honda            17
Nissan           17
Volkswagen       15
Chrysler         15
Dodge            13
Mitsubishi       13
Volvo            12
Jaguar           12
Hyundai          12
Subaru           11
Pontiac          11
Mazda            11
Lexus            11
Kia              11
Buick             9
Mercury           9
Lincoln           9
Saturn            8
Cadillac          8
Suzuki            8
Infiniti          8
GMC               8
Acura             7
Porsche           7
Saab              7
Land Rover        3
Oldsmobile        3
Jeep              3
Scion             2
Isuzu             2
MINI              2
Hummer            1
Name: count, dtype: int64

In [57]:
#Montrer les enregistrements où Oringin = Asia / Europe

data[data['Origin'] .isin(['Asia', 'Europe'])]
data.head(100)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Chrysler,Sebring Touring 4dr,Sedan,USA,Front,"$21,840","$20,284",2.7,6.0,200.0,21.0,28.0,3222.0,108.0,191.0
96,Chrysler,300M 4dr,Sedan,USA,Front,"$29,865","$27,797",3.5,6.0,250.0,18.0,27.0,3581.0,113.0,198.0
97,Chrysler,Concorde LX 4dr,Sedan,USA,Front,"$24,130","$22,452",2.7,6.0,200.0,21.0,29.0,3479.0,113.0,208.0
98,Chrysler,Concorde LXi 4dr,Sedan,USA,Front,"$26,860","$24,909",3.5,6.0,232.0,19.0,27.0,3548.0,113.0,208.0
99,Chrysler,PT Cruiser GT 4dr,Sedan,USA,Front,"$25,955","$24,172",2.4,4.0,220.0,21.0,27.0,3217.0,103.0,169.0

In [61]:
#enlever des enregistrements non-désirés (weight > 4000)
data[~(data['Weight'] > 4000)]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225.0,18.0,24.0,3893.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0

In [68]:
#augmenter les valeurs de MPG_city de 3 
data['MPG_City'] = data['MPG_City'].apply(lambda x:x+3)

In [69]:
data

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,26.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,33.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,31.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,29.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,27.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197.0,30.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242.0,29.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268.0,28.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170.0,31.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208.0,29.0,27.0,3823.0,109.0,186.0