In [1]:
#Import des différentes librairies
import pandas as pd 
import numpy as np

In [3]:

file_paths = r"C:\Users\fredd\OneDrive\Bureau\Datasets data\Lego\sets.csv"

sets = pd.read_csv(file_paths)

sets

,set_num,name,year,theme_id,num_parts,img_url
0,001-1,Gears,1965,1,43,https://cdn.rebrickable.com/media/sets/001-1.jpg
1,0011-2,Town Mini-Figures,1979,67,12,https://cdn.rebrickable.com/media/sets/0011-2.jpg
2,0011-3,Castle 2 for 1 Bonus Offer,1987,199,0,https://cdn.rebrickable.com/media/sets/0011-3.jpg
3,0012-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0012-1.jpg
4,0013-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0013-1.jpg
...,...,...,...,...,...,...
22192,XWING-1,Mini X-Wing Fighter,2019,158,60,https://cdn.rebrickable.com/media/sets/xwing-1...
22193,XWING-2,X-Wing Trench Run,2019,158,52,https://cdn.rebrickable.com/media/sets/xwing-2...
22194,YODACHRON-1,Yoda Chronicles Promotional Set,2013,158,413,https://cdn.rebrickable.com/media/sets/yodachr...
22195,YTERRIER-1,Yorkshire Terrier,2018,598,0,https://cdn.rebrickable.com/media/sets/yterrie...
22196,ZX8000-1,ZX 8000 LEGO Sneaker,2020,501,0,https://cdn.rebrickable.com/media/sets/zx8000-...

In [4]:
file_patht = r"C:\Users\fredd\OneDrive\Bureau\Datasets data\Lego\themes.csv"
themes = pd.read_csv(file_patht)
themes

      id                   name  parent_id
0      1                Technic        NaN
1      3            Competition        1.0
2      4         Expert Builder        1.0
3     16             RoboRiders        1.0
4     17         Speed Slammers        1.0
..   ...                    ...        ...
464  749               Dreamzzz        NaN
465  750        Marvel Series 2      535.0
466  751                 Marvel      207.0
467  752        Animal Crossing        NaN
468  753  Series 25 Minifigures      535.0

[469 rows x 3 columns]

In [5]:
sets.head(10)

,set_num,name,year,theme_id,num_parts,img_url
0,001-1,Gears,1965,1,43,https://cdn.rebrickable.com/media/sets/001-1.jpg
1,0011-2,Town Mini-Figures,1979,67,12,https://cdn.rebrickable.com/media/sets/0011-2.jpg
2,0011-3,Castle 2 for 1 Bonus Offer,1987,199,0,https://cdn.rebrickable.com/media/sets/0011-3.jpg
3,0012-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0012-1.jpg
4,0013-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0013-1.jpg
5,0014-1,Space Mini-Figures,1979,143,2,https://cdn.rebrickable.com/media/sets/0014-1.jpg
6,0015-1,Space Mini-Figures,1979,143,18,https://cdn.rebrickable.com/media/sets/0015-1.jpg
7,0016-1,Castle Mini Figures,1979,189,15,https://cdn.rebrickable.com/media/sets/0016-1.jpg
8,002-1,4.5V Samsonite Gears Motor Set,1965,1,3,https://cdn.rebrickable.com/media/sets/002-1.jpg
9,002253963-1,Legend of Chima: Corbeaux et Gorilles,2013,497,4,https://cdn.rebrickable.com/media/sets/0022539...

In [6]:
sets.tail(10)

,set_num,name,year,theme_id,num_parts,img_url
22187,XBOXGAME-1,Batman the Videogame - Xbox 360,2008,742,0,https://cdn.rebrickable.com/media/sets/xboxgam...
22188,XBOXGAME-2,Bionicle Heroes - Xbox 360,2006,742,0,https://cdn.rebrickable.com/media/sets/xboxgam...
22189,XBOXGAME-3,DC Super-Villains - Xbox One,2018,742,0,https://cdn.rebrickable.com/media/sets/xboxgam...
22190,XBOXGAME-9,Star Wars: The Video Game - Xbox,2005,742,0,https://cdn.rebrickable.com/media/sets/xboxgam...
22191,XMASTREE-1,Christmas Tree,2019,410,26,https://cdn.rebrickable.com/media/sets/xmastre...
22192,XWING-1,Mini X-Wing Fighter,2019,158,60,https://cdn.rebrickable.com/media/sets/xwing-1...
22193,XWING-2,X-Wing Trench Run,2019,158,52,https://cdn.rebrickable.com/media/sets/xwing-2...
22194,YODACHRON-1,Yoda Chronicles Promotional Set,2013,158,413,https://cdn.rebrickable.com/media/sets/yodachr...
22195,YTERRIER-1,Yorkshire Terrier,2018,598,0,https://cdn.rebrickable.com/media/sets/yterrie...
22196,ZX8000-1,ZX 8000 LEGO Sneaker,2020,501,0,https://cdn.rebrickable.com/media/sets/zx8000-...

In [7]:
sets.dtypes

set_num      object
name         object
year          int64
theme_id      int64
num_parts     int64
img_url      object
dtype: object

In [9]:
sets.isnull().sum()

set_num      0
name         0
year         0
theme_id     0
num_parts    0
img_url      0
dtype: int64

In [10]:
themes.isnull().sum()

id             0
name           0
parent_id    145
dtype: int64

In [12]:
sets.shape

(22197, 6)

In [14]:
len(sets.columns)

6

In [15]:
len(sets)

22197

In [16]:
sets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22197 entries, 0 to 22196
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   set_num    22197 non-null  object
 1   name       22197 non-null  object
 2   year       22197 non-null  int64
 3   theme_id   22197 non-null  int64
 4   num_parts  22197 non-null  int64
 5   img_url    22197 non-null  object
dtypes: int64(3), object(3)
memory usage: 1.0+ MB

In [18]:
#Jointure 

sets_themes = pd.merge(sets, themes, how = 'left', left_on = 'theme_id', right_on = 'id', suffixes = ('_sets', '_themes'))
sets_themes.head()

,set_num,name_sets,year,theme_id,num_parts,img_url,id,name_themes,parent_id
0,001-1,Gears,1965,1,43,https://cdn.rebrickable.com/media/sets/001-1.jpg,1,Technic,NaN
1,0011-2,Town Mini-Figures,1979,67,12,https://cdn.rebrickable.com/media/sets/0011-2.jpg,67,Classic Town,50.0
2,0011-3,Castle 2 for 1 Bonus Offer,1987,199,0,https://cdn.rebrickable.com/media/sets/0011-3.jpg,199,Lion Knights,186.0
3,0012-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0012-1.jpg,143,Supplemental,126.0
4,0013-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0013-1.jpg,143,Supplemental,126.0

In [20]:
sets_themes.columns

Index(['set_num', 'name_sets', 'year', 'theme_id', 'num_parts', 'img_url',
       'id', 'name_themes', 'parent_id'],
      dtype='object')

In [32]:
#nombre total de num_parts par themes
num_parts_per_theme = sets_themes.groupby('name_themes').sum().reset_index()
num_parts_per_theme = num_parts_per_theme[['name_themes', 'num_parts']].sort_values('num_parts', ascending = False)
num_parts_per_theme

                     name_themes  num_parts
327                      Technic     252274
312                    Star Wars     247414
126                      Friends     122542
223                      Ninjago     118448
357    Ultimate Collector Series     105949
..                           ...        ...
239                   Plush Toys          0
241       Posters and Art Prints          0
6                    Adventurers          0
283        Series 25 Minifigures          0
259  Role Play Toys and Costumes          0

[383 rows x 2 columns]

In [34]:
#nombre total de num_parts par année
num_parts_per_theme = sets_themes.groupby('year').sum().reset_index()
num_parts_per_theme = num_parts_per_theme[['year', 'num_parts']].sort_values('num_parts', ascending = False)
num_parts_per_theme

    year  num_parts
72  2023     299015
71  2022     280895
70  2021     265491
69  2020     212152
68  2019     192061
..   ...        ...
5   1956        295
3   1954        117
8   1959         79
2   1953         50
1   1950          6

[74 rows x 2 columns]

In [36]:
#Combien de sets crées par siècle dans le dataset 
sets_themes.head()

,set_num,name_sets,year,theme_id,num_parts,img_url,id,name_themes,parent_id
0,001-1,Gears,1965,1,43,https://cdn.rebrickable.com/media/sets/001-1.jpg,1,Technic,NaN
1,0011-2,Town Mini-Figures,1979,67,12,https://cdn.rebrickable.com/media/sets/0011-2.jpg,67,Classic Town,50.0
2,0011-3,Castle 2 for 1 Bonus Offer,1987,199,0,https://cdn.rebrickable.com/media/sets/0011-3.jpg,199,Lion Knights,186.0
3,0012-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0012-1.jpg,143,Supplemental,126.0
4,0013-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0013-1.jpg,143,Supplemental,126.0

In [40]:
#Pourcentage des de sets crées au 21è siecle avec le thème Trains
sets_themes['century'] = np.where(sets_themes['year'] > 2000, '21st Century','20th Century' )
sets_themes.head(10)

,set_num,name_sets,year,theme_id,num_parts,img_url,id,name_themes,parent_id,century
0,001-1,Gears,1965,1,43,https://cdn.rebrickable.com/media/sets/001-1.jpg,1,Technic,NaN,20th Century
1,0011-2,Town Mini-Figures,1979,67,12,https://cdn.rebrickable.com/media/sets/0011-2.jpg,67,Classic Town,50.0,20th Century
2,0011-3,Castle 2 for 1 Bonus Offer,1987,199,0,https://cdn.rebrickable.com/media/sets/0011-3.jpg,199,Lion Knights,186.0,20th Century
3,0012-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0012-1.jpg,143,Supplemental,126.0,20th Century
4,0013-1,Space Mini-Figures,1979,143,12,https://cdn.rebrickable.com/media/sets/0013-1.jpg,143,Supplemental,126.0,20th Century
5,0014-1,Space Mini-Figures,1979,143,2,https://cdn.rebrickable.com/media/sets/0014-1.jpg,143,Supplemental,126.0,20th Century
6,0015-1,Space Mini-Figures,1979,143,18,https://cdn.rebrickable.com/media/sets/0015-1.jpg,143,Supplemental,126.0,20th Century
7,0016-1,Castle Mini Figures,1979,189,15,https://cdn.rebrickable.com/media/sets/0016-1.jpg,189,Classic Castle,186.0,20th Century
8,002-1,4.5V Samsonite Gears Motor Set,1965,1,3,https://cdn.rebrickable.com/media/sets/002-1.jpg,1,Technic,NaN,20th Century
9,002253963-1,Legend of Chima: Corbeaux et Gorilles,2013,497,4,https://cdn.rebrickable.com/media/sets/0022539...,497,Books,NaN,21st Century

In [45]:
century = sets_themes.groupby('century').count().reset_index()
century[['century', 'set_num']].sort_values('set_num', ascending = False)

        century  set_num
1  21st Century    17142
0  20th Century     5055

In [63]:
sets_themes_trains = sets_themes[(sets_themes['century'] == '21st Century') & (sets_themes['name_themes'].str.contains('Trains'))]

In [64]:
sets_themes_trains.shape[0]

65

In [65]:
sets_themes.shape[0]

22197

In [66]:
sets_themes_trains.shape[0]/sets_themes.shape[0]*100

0.29283236473397306

In [69]:
# Pourcentage des de sets crées au 21è siecle avec le thème Disney
sets_themes_disney = sets_themes[(sets_themes['century'] == '21st Century') & (sets_themes['name_themes'].str.contains('Disney'))]

In [70]:
sets_themes_disney.shape[0]

246

In [71]:
sets_themes_disney.shape[0]/sets_themes.shape[0]*100

1.108257872685498

In [86]:
century_21 = sets_themes[sets_themes['century'] == '21st Century']
century_21.head()

,set_num,name_sets,year,theme_id,num_parts,img_url,id,name_themes,parent_id,century
9,002253963-1,Legend of Chima: Corbeaux et Gorilles,2013,497,4,https://cdn.rebrickable.com/media/sets/0022539...,497,Books,NaN,21st Century
17,010423-1,The Majestic Horse,2023,721,0,https://cdn.rebrickable.com/media/sets/010423-...,721,Icons,NaN,21st Century
25,0241187567-1,Ninjago: Build Your Own Adventure,2015,497,74,https://cdn.rebrickable.com/media/sets/0241187...,497,Books,NaN,21st Century
26,0241357594-1,Star Wars: Build Your Own Adventure: Galactic ...,2019,497,70,https://cdn.rebrickable.com/media/sets/0241357...,497,Books,NaN,21st Century
66,0756668530-1,Atlantis: Brickmaster,2010,497,157,https://cdn.rebrickable.com/media/sets/0756668...,497,Books,NaN,21st Century

In [88]:
century_21.groupby('year').sum()

,set_num,name_sets,theme_id,num_parts,img_url,id,name_themes,parent_id,century
year,,,,,,,,,
2001,10000-110001-110002-110003-110004-110005-11000...,Guarded InnMetrolinerRailroad Club Car1 x 2 Sa...,170896,39900,https://cdn.rebrickable.com/media/sets/10000-1...,170896,Lion KnightsTrainTrainBulk BricksBulk BricksBu...,78402.0,21st Century21st Century21st Century21st Centu...
2002,10020-110020-210022-110023-110024-110025-11002...,Santa Fe Super ChiefSanta Fe Super Chief - Lim...,249136,55014,https://cdn.rebrickable.com/media/sets/10020-1...,249136,9V9V9VBionicleCreator Expert9VUltimate Collect...,149909.0,21st Century21st Century21st Century21st Centu...
2003,10010-110021-110027-110029-110041-110042-11005...,Assorted Yellow BricksU.S.S. ConstellationTrai...,196315,67742,https://cdn.rebrickable.com/media/sets/10010-1...,196315,Bulk BricksHobby SetsWorld CityDiscoveryTownSe...,97009.0,21st Century21st Century21st Century21st Centu...
2004,10081-110082-110083-110116-110117-110118-11013...,Birthday Pack HeartBirthday Pack DaisyBirthday...,163561,60295,https://cdn.rebrickable.com/media/sets/10081-1...,163561,ClikitsClikitsClikitsClikitsClikitsClikitsUlti...,74771.0,21st Century21st Century21st Century21st Centu...
2005,10128-210143-110144-110152-210168-110169-11017...,Train Level CrossingDeath Star IISandcrawlerMa...,133777,70726,https://cdn.rebrickable.com/media/sets/10128-2...,133777,World CityUltimate Collector SeriesUltimate Co...,63790.0,21st Century21st Century21st Century21st Centu...
2006,10106-110152-310173-110174-110175-110176-11017...,SnowflakeMaersk Line Container Ship 2006 Editi...,162066,73417,https://cdn.rebrickable.com/media/sets/10106-1...,162066,ChristmasCreator ExpertCreator ExpertUltimate ...,86994.0,21st Century21st Century21st Century21st Centu...
2007,10178-110179-110181-110182-110183-110190-12000...,Motorized Walking AT-ATMillennium FalconEiffel...,188196,79567,https://cdn.rebrickable.com/media/sets/10178-1...,188196,Ultimate Collector SeriesUltimate Collector Se...,110840.0,21st Century21st Century21st Century21st Centu...
2008,1000368666-110184-110185-110186-110187-110188-...,Batman the Videogame - PSPTown PlanGreen Groce...,172663,84000,https://cdn.rebrickable.com/media/sets/1000368...,172663,Video Games and AccessoriesTown PlanModular Bu...,87098.0,21st Century21st Century21st Century21st Centu...
2009,0756672805-110193-110194-110195-110196-110197-...,Pirates: BrickmasterMedieval Market VillageEme...,199302,82957,https://cdn.rebrickable.com/media/sets/0756672...,199302,BooksFantasy EraCreator ExpertUltimate Collect...,92823.0,21st Century21st Century21st Century21st Centu...
2010,0756668530-110155-110210-110211-110212-110213-...,Atlantis: BrickmasterMaersk Line Container Shi...,202269,95352,https://cdn.rebrickable.com/media/sets/0756668...,202269,BooksCreator ExpertPirates IIModular Buildings...,124869.0,21st Century21st Century21st Century21st Centu...
2011,0756682762-110217-110218-110219-110220-110221-...,Ninjago: BrickmasterDiagon AlleyPet ShopMaersk...,265532,83272,https://cdn.rebrickable.com/media/sets/0756682...,265532,BooksHarry PotterModular BuildingsCreator Expe...,143334.0,21st Century21st Century21st Century21st Centu...
2012,0756692571-11000229927-110223-110224-110225-11...,Harry Potter: Characters of the Magical WorldH...,338852,95737,https://cdn.rebrickable.com/media/sets/0756692...,338852,BooksVideo Games and AccessoriesKingdomsModula...,180877.0,21st Century21st Century21st Century21st Centu...
2013,002253963-11000430096-81000565897-510232-11023...,Legend of Chima: Corbeaux et GorillesMarvel Su...,345282,110202,https://cdn.rebrickable.com/media/sets/0022539...,345282,BooksVideo Games and AccessoriesVideo Games an...,186794.0,21st Century21st Century21st Century21st Centu...
2014,10241-110242-110243-110244-110245-110521-11052...,Maersk Line Triple-EMINI CooperParisian Restau...,483410,131149,https://cdn.rebrickable.com/media/sets/10241-1...,483410,Creator ExpertCreator ExpertModular BuildingsC...,248818.0,21st Century21st Century21st Century21st Centu...
2015,0241187567-110000549412-11000565140-1100056519...,Ninjago: Build Your Own AdventureJurassic Worl...,437314,149130,https://cdn.rebrickable.com/media/sets/0241187...,437314,BooksVideo Games and AccessoriesVideo Games an...,168891.0,21st Century21st Century21st Century21st Centu...
2016,1000565740-11000565742-11000565765-11000577871...,Marvel Avengers - Xbox OneMarvel Avengers - PS...,465554,159449,https://cdn.rebrickable.com/media/sets/1000565...,465554,Video Games and AccessoriesVideo Games and Acc...,176248.0,21st Century21st Century21st Century21st Centu...
2017,1000643461-11000648795-11000692713-110255-1102...,Marvel Super Heroes 2 - Xbox OneMarvel Super H...,510302,178707,https://cdn.rebrickable.com/media/sets/1000643...,510302,Video Games and AccessoriesVideo Games and Acc...,241340.0,21st Century21st Century21st Century21st Centu...
2018,1000709804-11000709806-110260-110261-110262-11...,DC Super-Villains - Nintendo SwitchDC Super-Vi...,483323,171739,https://cdn.rebrickable.com/media/sets/1000709...,483323,Video Games and AccessoriesVideo Games and Acc...,170287.0,21st Century21st Century21st Century21st Centu...
2019,0241357594-11000704831-21000704832-13100070980...,Star Wars: Build Your Own Adventure: Galactic ...,551674,192061,https://cdn.rebrickable.com/media/sets/0241357...,551674,BooksVideo Games and AccessoriesVideo Games an...,239319.0,21st Century21st Century21st Century21st Centu...
2020,10270-110271-110272-110273-110274-110275-11027...,BookshopFiat 500Old Trafford - Manchester Unit...,539029,212152,https://cdn.rebrickable.com/media/sets/10270-1...,539029,Modular BuildingsCreator ExpertCreator ExpertI...,187617.0,21st Century21st Century21st Century21st Centu...
2021,10278-110279-110280-110281-110282-110282-21028...,Police StationVolkswagen T2 Camper VanFlower B...,606435,265491,https://cdn.rebrickable.com/media/sets/10278-1...,606435,Modular BuildingsIconsIconsIconsIconsIconsIcon...,142465.0,21st Century21st Century21st Century21st Centu...
2022,100871-110297-110298-110299-110300-110302-1103...,90 Years of Play Metal Key ChainBoutique Hotel...,528640,280895,https://cdn.rebrickable.com/media/sets/100871-...,528640,Key ChainModular BuildingsIconsIconsIconsIcons...,151250.0,21st Century21st Century21st Century21st Centu...
2023,010423-110312-110313-110314-110315-110316-1103...,The Majestic HorseJazz ClubWildflower BouquetD...,509193,299015,https://cdn.rebrickable.com/media/sets/010423-...,509193,IconsModular BuildingsIconsIconsIconsIconsIcon...,133984.0,21st Century21st Century21st Century21st Centu...
2024,10327-110328-110412-110413-110414-110415-11041...,Dune Atreides Royal OrnithopterBouquet of Rose...,105146,1623,https://cdn.rebrickable.com/media/sets/10327-1...,105146,IconsIconsDuploDuploDuploDuploDuploCarsDuploDu...,13840.0,21st Century21st Century21st Century21st Centu...

In [102]:
Pop_themes = century_21.groupby(['year', 'name_themes']).count().sort_values(by = ['set_num'], ascending = False).reset_index()
Pop_themes = Pop_themes[['year', 'name_themes','set_num']]
Pop_themes.drop_duplicates('year')

     year name_themes  set_num
0    2021        Gear      149
1    2014     Technic      116
2    2023       Books      109
4    2022       Books       97
5    2017       Books       81
6    2016       Books       81
7    2020       Books       80
8    2019       Books       76
9    2018   Star Wars       69
11   2015   Star Wars       69
12   2002     Technic       65
13   2003    Bionicle       64
30   2006    Bionicle       50
31   2004    Bionicle       50
34   2013       Books       49
44   2012     Ninjago       47
53   2001    Bionicle       45
58   2010   Key Chain       44
59   2011     Ninjago       43
63   2009      Racers       42
74   2008    Bionicle       39
77   2005    Bionicle       38
85   2007   Key Chain       36
124  2024        City       27